#docs-private-to-public-sync
notify:
  - slack: "$SLACK_CHANNEL"
    if: build.state != "passed"
env:
  PUBLIC_REPO: https://github.com/buildkite/docs.git
steps:
  - label: Sync to public mirror
    branches: main
    commands: |
      echo "+++ :git: Syncing to public mirror"

      git push "${PUBLIC_REPO}" ${BUILDKITE_COMMIT}:main
